### ISSUE TITLE
write specific functions to translate hubverse model output to different scoringutils prediction type dfs

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubEvals#12]
These helper functions would be called by a more general translation function. Output types needed to support

- [ ] quantile
- [ ] sample 
- [ ] cdf
- [ ] pmf --> something that doesn't exist yet in scoringutils (see [issue](https://github.com/epiforecasts/scoringutils/issues/604))
- [ ] mean/median (hubverse) --> point (scoringutils)

migrated from https://github.com/epiforecasts/scoringutils/issues/605

**Comment by bsweger** [comment]
We split this into a single issue for each model_output type, so closing this one.

See instead:

- #22 (quantile)
- #23 (cdf)
- #24 (pmf stub)
- #25 (mean/median)
- #26 (sample)
