### ISSUE TITLE
change template issue

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubEvals#15]
When you [click to open a new issue](https://github.com/Infectious-Disease-Modeling-Hubs/hubEvals/issues/new/choose) there is an irrelevant template issue that is about updating Docs to hubStyle. I think this should be removed.

![image](https://github.com/Infectious-Disease-Modeling-Hubs/hubEvals/assets/1280767/2c7800b8-e6c0-45a3-9645-6f427aee04dd)

**Comment by nickreich** [comment]
maybe impacts other hubs as well?

**Comment by annakrystalli** [comment]
Sorry. I've just placed it temporally as an organisation GitHub issue template so I can access it in all repos as I go through. Will be deleted on Monday when I'm done

**Comment by annakrystalli** [comment]
Deleted in https://github.com/Infectious-Disease-Modeling-Hubs/.github/commit/5eb8da745ef12f6e6da42cea3119239f4f0449d6
