### ISSUE TITLE
update documentation about example data

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubEvals#19]
Depending on results of discussions about example data, we might want to consider updating the example data objects. But if we keep them more or less as is, we should probably update the documentation about the existing example data to point explicitly towards the example-simple-forecast-hub as the source of the data. Currently the documentation points towards the COVID-19 Forecast Hub as the 'source' which is sort of true, as it is the root source of the data, but not the most proximal source used in the R scripts in `data-raw`.

**Comment by elray1** [comment]
I'm closing this issue since I think it's unnecessary in light of the planned (and almost ready to use) [hubExamples](https://github.com/Infectious-Disease-Modeling-Hubs/hubExamples) data package.
